"""Khoi tao database

Revision ID: 11837c59bfb5
Revises:
Create Date: 2026-07-16 11:54:26.011733

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "11837c59bfb5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
