"""them word_list user_admin

Revision ID: f456b64fc725
Revises: 6cbb09b8bcf1
Create Date: 2026-07-26 11:23:47.952404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  # dùng cho AutoString type


# revision identifiers, used by Alembic.
revision: str = 'f456b64fc725'
down_revision: Union[str, Sequence[str], None] = '6cbb09b8bcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Enum('N5', 'N4', 'N3', 'N2', 'N1', name='jlptlevel'), nullable=False),
    sa.Column('source', sa.Enum('MIMIKARA', 'TANGO', name='wordsource'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_lists_name'), 'word_lists', ['name'], unique=False)
    op.create_table('user_word_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_list_id'], ['word_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_list_id', name='uq_uwl_user_list')
    )
    op.create_table('word_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_list_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_list_id'], ['word_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_list_id', 'word_id', name='uq_wle_list_word')
    )
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('word_list_entries')
    op.drop_table('user_word_lists')
    op.drop_index(op.f('ix_word_lists_name'), table_name='word_lists')
    op.drop_table('word_lists')
    # ### end Alembic commands ###
